version: "3.3"

services:
  nginx:
    image: nginx
    depends_on:
      - deno
      - next
    volumes:
      - ./nginx:/etc/nginx/conf.d
    container_name: nginx
    ports:
      - "80:80"
    expose:
      - 80

  next:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose: 
      - 3000

  deno:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose: 
      - 8000

  deno_second:
    build:
      context: ./server2
      dockerfile: Dockerfile
    expose: 
      - 8000